# Generated by Django 2.1.2 on 2018-10-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'verbose_name': 'Дом', 'verbose_name_plural': 'Дома'},
        ),
        migrations.AlterField(
            model_name='house',
            name='house_area',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='Площадь дома'),
        ),
        migrations.AlterField(
            model_name='house',
            name='house_description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='house',
            name='house_name',
            field=models.CharField(max_length=20, verbose_name='Название'),
        ),
    ]
